import datetime
from sqlalchemy.orm import Session

from backend.app.auth.security import get_password_hash
from backend.app.database.session import Base, SessionLocal, engine
from backend.app.models.models import (
    Activity,
    City,
    Expense,
    Favorite,
    ItineraryActivity,
    Notification,
    SharedTrip,
    Trip,
    TripStop,
    User,
)
from backend.app.services.image_service import CITY_IMAGES, get_category_image, get_city_image

CITIES_DATA = [
    {
        "name": "Jaipur",
        "state": "Rajasthan",
        "region": "North",
        "cost_index": "Moderate",
        "popularity": 96,
        "latitude": 26.9124,
        "longitude": 75.7873,
        "best_suited_interests": "History,Culture,Photography,Shopping",
        "description": "The Pink City of India, world-famous for its majestic forts, grand palaces, vibrant bazaars, and opulent royal heritage.",
    },
    {
        "name": "Udaipur",
        "state": "Rajasthan",
        "region": "North",
        "cost_index": "Luxury",
        "popularity": 94,
        "latitude": 24.5854,
        "longitude": 73.7125,
        "best_suited_interests": "Culture,Photography,Nature,History",
        "description": "The City of Lakes, crowned by sparkling waters, romantic marble palaces, and scenic views of the Aravalli hills.",
    },
    {
        "name": "Jodhpur",
        "state": "Rajasthan",
        "region": "North",
        "cost_index": "Moderate",
        "popularity": 90,
        "latitude": 26.2389,
        "longitude": 73.0243,
        "best_suited_interests": "History,Culture,Photography",
        "description": "The Blue City, overlooked by the colossal Mehrangarh Fort and famed for its azure houses and bustling spice markets.",
    },
    {
        "name": "Jaisalmer",
        "state": "Rajasthan",
        "region": "North",
        "cost_index": "Moderate",
        "popularity": 89,
        "latitude": 26.9157,
        "longitude": 70.9083,
        "best_suited_interests": "Adventure,History,Culture,Photography",
        "description": "The Golden City at the heart of the Thar Desert, featuring yellow sandstone architecture and golden rolling sand dunes.",
    },
    {
        "name": "Ahmedabad",
        "state": "Gujarat",
        "region": "West",
        "cost_index": "Budget",
        "popularity": 88,
        "latitude": 23.0225,
        "longitude": 72.5714,
        "best_suited_interests": "Culture,Food,History",
        "description": "India's first UNESCO World Heritage City, famous for the Sabarmati Ashram, intricate stepwells, and mouth-watering Gujarati cuisine.",
    },
    {
        "name": "Mumbai",
        "state": "Maharashtra",
        "region": "West",
        "cost_index": "Luxury",
        "popularity": 98,
        "latitude": 19.0760,
        "longitude": 72.8777,
        "best_suited_interests": "Nightlife,Food,Entertainment,Shopping,Culture",
        "description": "The bustling financial capital of India, home to Bollywood, the iconic Gateway of India, and vibrant coastal promenades.",
    },
    {
        "name": "Delhi",
        "state": "Delhi",
        "region": "North",
        "cost_index": "Moderate",
        "popularity": 97,
        "latitude": 28.6139,
        "longitude": 77.2090,
        "best_suited_interests": "History,Food,Culture,Shopping",
        "description": "The vibrant capital of India, steeped in millennia of history, epic Mughal monuments, and legendary street food markets.",
    },
    {
        "name": "Goa",
        "state": "Goa",
        "region": "West",
        "cost_index": "Moderate",
        "popularity": 99,
        "latitude": 15.2993,
        "longitude": 74.1240,
        "best_suited_interests": "Adventure,Nightlife,Nature,Food",
        "description": "India's premier coastal paradise, celebrated for golden sandy beaches, lively beach shacks, water sports, and Portuguese heritage.",
    },
    {
        "name": "Panaji",
        "state": "Goa",
        "region": "West",
        "cost_index": "Moderate",
        "popularity": 87,
        "latitude": 15.4909,
        "longitude": 73.8278,
        "best_suited_interests": "Culture,Photography,Food",
        "description": "The charming capital of Goa, renowned for colorful Latin Quarter Fontainhas, river cruises on Mandovi, and colonial churches.",
    },
    {
        "name": "Varanasi",
        "state": "Uttar Pradesh",
        "region": "North",
        "cost_index": "Budget",
        "popularity": 95,
        "latitude": 25.3176,
        "longitude": 82.9739,
        "best_suited_interests": "Culture,History,Photography",
        "description": "One of the world's oldest continuously inhabited sacred cities, famed for mesmerizing Ganga Aarti rituals and ancient ghats.",
    },
    {
        "name": "Agra",
        "state": "Uttar Pradesh",
        "region": "North",
        "cost_index": "Moderate",
        "popularity": 98,
        "latitude": 27.1767,
        "longitude": 78.0081,
        "best_suited_interests": "History,Photography,Culture",
        "description": "Home to the world-wonder Taj Mahal, Agra Fort, and Fatehpur Sikri, representing the zenith of Mughal art and architecture.",
    },
    {
        "name": "Bengaluru",
        "state": "Karnataka",
        "region": "South",
        "cost_index": "Moderate",
        "popularity": 92,
        "latitude": 12.9716,
        "longitude": 77.5946,
        "best_suited_interests": "Food,Nightlife,Nature,Shopping",
        "description": "The Garden City and Silicon Valley of India, known for lush parks, vibrant craft breweries, and pleasant year-round weather.",
    },
    {
        "name": "Hyderabad",
        "state": "Telangana",
        "region": "South",
        "cost_index": "Moderate",
        "popularity": 91,
        "latitude": 17.3850,
        "longitude": 78.4867,
        "best_suited_interests": "Food,History,Culture,Shopping",
        "description": "City of Pearls and Nizams, renowned worldwide for the Charminar, Golconda Fort, and authentic Hyderabadi Dum Biryani.",
    },
    {
        "name": "Chennai",
        "state": "Tamil Nadu",
        "region": "South",
        "cost_index": "Budget",
        "popularity": 89,
        "latitude": 13.0827,
        "longitude": 80.2707,
        "best_suited_interests": "Culture,Food,History,Nature",
        "description": "Gateway to South India, rich in classical Carnatic music, Dravidian temples, Marina Beach, and traditional South Indian cuisine.",
    },
    {
        "name": "Kolkata",
        "state": "West Bengal",
        "region": "East",
        "cost_index": "Budget",
        "popularity": 93,
        "latitude": 22.5726,
        "longitude": 88.3639,
        "best_suited_interests": "Culture,Food,History,Photography",
        "description": "The Cultural Capital of India, famed for colonial grandeur, Howrah Bridge, Durga Puja festivities, and delectable sweets.",
    },
    {
        "name": "Kochi",
        "state": "Kerala",
        "region": "South",
        "cost_index": "Moderate",
        "popularity": 93,
        "latitude": 9.9312,
        "longitude": 76.2673,
        "best_suited_interests": "Culture,Nature,Food,Photography",
        "description": "Queen of the Arabian Sea, featuring historic Fort Kochi, Chinese fishing nets, Kathakali dance, and serene backwater canals.",
    },
    {
        "name": "Srinagar",
        "state": "Jammu & Kashmir",
        "region": "North",
        "cost_index": "Moderate",
        "popularity": 96,
        "latitude": 34.0837,
        "longitude": 74.7973,
        "best_suited_interests": "Nature,Photography,Culture,Adventure",
        "description": "Paradise on Earth, celebrated for romantic Shikara rides on Dal Lake, houseboats, Mughal gardens, and snow-capped peaks.",
    },
    {
        "name": "Amritsar",
        "state": "Punjab",
        "region": "North",
        "cost_index": "Budget",
        "popularity": 95,
        "latitude": 31.6340,
        "longitude": 74.8723,
        "best_suited_interests": "Culture,Food,History",
        "description": "Spiritual capital of Sikhism, home to the resplendent Golden Temple (Harmandir Sahib), Wagah Border, and rich Punjabi hospitality.",
    },
    {
        "name": "Mysuru",
        "state": "Karnataka",
        "region": "South",
        "cost_index": "Budget",
        "popularity": 90,
        "latitude": 12.2958,
        "longitude": 76.6394,
        "best_suited_interests": "Culture,History,Photography",
        "description": "The City of Palaces, famous for the illuminated Mysore Palace, Chamundi Hill, sandalwood, and royal Dasara festivities.",
    },
    {
        "name": "Nashik",
        "state": "Maharashtra",
        "region": "West",
        "cost_index": "Moderate",
        "popularity": 86,
        "latitude": 19.9975,
        "longitude": 73.7898,
        "best_suited_interests": "Nature,Culture,Food",
        "description": "Wine Capital of India nestled on the banks of Godavari, with Sula Vineyards, Kumbh Mela ghats, and Trimbakeshwar temple.",
    },
    {
        "name": "Chandigarh",
        "state": "Punjab / Haryana",
        "region": "North",
        "cost_index": "Moderate",
        "popularity": 88,
        "latitude": 30.7333,
        "longitude": 76.7794,
        "best_suited_interests": "Nature,Culture,Shopping",
        "description": "India's first planned modern city designed by Le Corbusier, famous for Sukhna Lake, Rose Garden, and Nek Chand's Rock Garden.",
    },
    {
        "name": "Dehradun",
        "state": "Uttarakhand",
        "region": "North",
        "cost_index": "Moderate",
        "popularity": 87,
        "latitude": 30.3165,
        "longitude": 78.0322,
        "best_suited_interests": "Nature,Adventure,Culture",
        "description": "Picturesque Doon Valley nestled between Himalayas and Shivaliks, gateway to Mussoorie, Rishikesh, and Haridwar.",
    },
    {
        "name": "Ooty",
        "state": "Tamil Nadu",
        "region": "South",
        "cost_index": "Moderate",
        "popularity": 93,
        "latitude": 11.4102,
        "longitude": 76.6950,
        "best_suited_interests": "Nature,Photography,Family",
        "description": "Queen of Nilgiris hill stations, featuring tea plantations, toy train rides, botanical gardens, and mist-covered valleys.",
    },
    {
        "name": "Darjeeling",
        "state": "West Bengal",
        "region": "East",
        "cost_index": "Moderate",
        "popularity": 94,
        "latitude": 27.0410,
        "longitude": 88.2663,
        "best_suited_interests": "Nature,Photography,Adventure",
        "description": "Himalayan jewel overlooking Mt Kanchenjunga, famed worldwide for aromatic black tea, ropeways, and UNESCO toy train.",
    },
    {
        "name": "Khajuraho",
        "state": "Madhya Pradesh",
        "region": "Central",
        "cost_index": "Moderate",
        "popularity": 91,
        "latitude": 24.8318,
        "longitude": 79.9199,
        "best_suited_interests": "History,Culture,Photography",
        "description": "UNESCO World Heritage site featuring stunning medieval Hindu and Jain temples with world-renowned intricate stone carvings.",
    },
]

ACTIVITIES_DATA = [
    # 1. JAIPUR (6 activities)
    {
        "city_name": "Jaipur",
        "name": "Amber Fort Guided Tour",
        "category": "Sightseeing",
        "duration_hours": 3.0,
        "estimated_cost": 500,
        "rating": 4.8,
        "popularity_score": 98,
        "image_url": "https://images.unsplash.com/photo-1605649487212-47bdab064df7?auto=format&fit=crop&w=800&q=80",
        "description": "Explore the majestic hilltop Amber Fort with sweeping views of Maota Lake and ornate Sheesh Mahal mirrors.",
    },
    {
        "city_name": "Jaipur",
        "name": "Hawa Mahal & Old City Walk",
        "category": "Photography",
        "duration_hours": 1.5,
        "estimated_cost": 200,
        "rating": 4.7,
        "popularity_score": 95,
        "image_url": "https://images.unsplash.com/photo-1599661046289-e31897846e41?auto=format&fit=crop&w=800&q=80",
        "description": "Admire the 953 honeycombed windows of Palace of Winds and photograph vibrant pink city alleys.",
    },
    {
        "city_name": "Jaipur",
        "name": "City Palace & Royal Museum",
        "category": "Culture",
        "duration_hours": 2.0,
        "estimated_cost": 700,
        "rating": 4.6,
        "popularity_score": 92,
        "image_url": "https://images.unsplash.com/photo-1615836245337-f5b9b2303f10?auto=format&fit=crop&w=800&q=80",
        "description": "Tour the residence of the Maharaja of Jaipur displaying royal armory, costumes, and courtyards.",
    },
    {
        "city_name": "Jaipur",
        "name": "Jantar Mantar Astronomical Observatory",
        "category": "History",
        "duration_hours": 1.5,
        "estimated_cost": 250,
        "rating": 4.6,
        "popularity_score": 89,
        "image_url": "https://images.unsplash.com/photo-1564507592333-c60657eea523?auto=format&fit=crop&w=800&q=80",
        "description": "Marvel at the world's largest stone sundial and ancient astronomical instruments at this UNESCO site.",
    },
    {
        "city_name": "Jaipur",
        "name": "Nahargarh Fort Sunset Trek",
        "category": "Adventure",
        "duration_hours": 2.5,
        "estimated_cost": 300,
        "rating": 4.9,
        "popularity_score": 96,
        "image_url": "https://images.unsplash.com/photo-1589308078059-be1415eab4c3?auto=format&fit=crop&w=800&q=80",
        "description": "Watch breathtaking panoramic sunsets over Jaipur city from the edge ramparts of Nahargarh.",
    },
    {
        "city_name": "Jaipur",
        "name": "Rajasthani Food & Chokhi Dhani Experience",
        "category": "Food",
        "duration_hours": 3.5,
        "estimated_cost": 1200,
        "rating": 4.8,
        "popularity_score": 94,
        "image_url": "https://images.unsplash.com/photo-1589301760014-d929f3979dbc?auto=format&fit=crop&w=800&q=80",
        "description": "Indulge in authentic Dal Baati Churma, traditional folk music, puppet shows, and camel rides.",
    },

    # 2. UDAIPUR (5 activities)
    {
        "city_name": "Udaipur",
        "name": "Lake Pichola Sunset Boat Ride",
        "category": "Sightseeing",
        "duration_hours": 1.5,
        "estimated_cost": 800,
        "rating": 4.9,
        "popularity_score": 99,
        "image_url": "https://images.unsplash.com/photo-1615836245337-f5b9b2303f10?auto=format&fit=crop&w=800&q=80",
        "description": "Cruise serene waters past Jag Mandir Island and the floating Taj Lake Palace as the sun sets.",
    },
    {
        "city_name": "Udaipur",
        "name": "City Palace Complex Tour",
        "category": "History",
        "duration_hours": 2.5,
        "estimated_cost": 450,
        "rating": 4.9,
        "popularity_score": 97,
        "image_url": "https://images.unsplash.com/photo-1615836245337-f5b9b2303f10?auto=format&fit=crop&w=800&q=80",
        "description": "Wander through Rajasthan's largest royal palace complex with panoramic balconies overlooking Lake Pichola.",
    },
    {
        "city_name": "Udaipur",
        "name": "Sajjangarh Monsoon Palace",
        "category": "Sightseeing",
        "duration_hours": 2.0,
        "estimated_cost": 300,
        "rating": 4.6,
        "popularity_score": 88,
        "image_url": "https://images.unsplash.com/photo-1599661046289-e31897846e41?auto=format&fit=crop&w=800&q=80",
        "description": "Perched high on Bansdara Mountain, offering 360-degree views of Udaipur lakes and the surrounding sanctuary.",
    },
    {
        "city_name": "Udaipur",
        "name": "Bagore Ki Haveli Folk Dance Show",
        "category": "Culture",
        "duration_hours": 1.5,
        "estimated_cost": 200,
        "rating": 4.8,
        "popularity_score": 93,
        "image_url": "https://images.unsplash.com/photo-1582510003544-4d00b7f74220?auto=format&fit=crop&w=800&q=80",
        "description": "Experience Dharohar folk dance, fire stunts, and puppet theatre on the historic waterfront ghats.",
    },
    {
        "city_name": "Udaipur",
        "name": "Udaipur Heritage Street Food Trail",
        "category": "Food",
        "duration_hours": 2.0,
        "estimated_cost": 400,
        "rating": 4.7,
        "popularity_score": 87,
        "image_url": "https://images.unsplash.com/photo-1601050690597-df0568f70950?auto=format&fit=crop&w=800&q=80",
        "description": "Taste local delicacies including Kachori, Mirchi Vada, Kulhad Chai, and traditional Ghevar.",
    },

    # 3. AHMEDABAD (5 activities)
    {
        "city_name": "Ahmedabad",
        "name": "Sabarmati Ashram Historical Visit",
        "category": "History",
        "duration_hours": 2.0,
        "estimated_cost": 50,
        "rating": 4.8,
        "popularity_score": 95,
        "image_url": "https://images.unsplash.com/photo-1596176530529-78163a4f7af2?auto=format&fit=crop&w=800&q=80",
        "description": "Walk the peaceful grounds where Mahatma Gandhi led India's freedom struggle and spun the Charkha.",
    },
    {
        "city_name": "Ahmedabad",
        "name": "Adalaj Stepwell Architectural Marvel",
        "category": "Photography",
        "duration_hours": 1.5,
        "estimated_cost": 100,
        "rating": 4.8,
        "popularity_score": 94,
        "image_url": "https://images.unsplash.com/photo-1589308078059-be1415eab4c3?auto=format&fit=crop&w=800&q=80",
        "description": "Descend into the 5-storey 15th-century subterranean stepwell with ornate Solanki stone carvings.",
    },
    {
        "city_name": "Ahmedabad",
        "name": "Old City Heritage Walking Tour",
        "category": "Culture",
        "duration_hours": 2.5,
        "estimated_cost": 350,
        "rating": 4.7,
        "popularity_score": 90,
        "image_url": "https://images.unsplash.com/photo-1582510003544-4d00b7f74220?auto=format&fit=crop&w=800&q=80",
        "description": "Explore medieval Pols (traditional gated neighborhoods), carved wooden bird feeders, and Jama Masjid.",
    },
    {
        "city_name": "Ahmedabad",
        "name": "Sabarmati Riverfront Evening Promenade",
        "category": "Nature",
        "duration_hours": 1.5,
        "estimated_cost": 100,
        "rating": 4.5,
        "popularity_score": 86,
        "image_url": "https://images.unsplash.com/photo-1506744038136-46273834b3fb?auto=format&fit=crop&w=800&q=80",
        "description": "Stroll along the landscaped riverfront, flower parks, and cycling tracks beside the river.",
    },
    {
        "city_name": "Ahmedabad",
        "name": "Manek Chowk Midnight Food Adventure",
        "category": "Food",
        "duration_hours": 2.0,
        "estimated_cost": 500,
        "rating": 4.9,
        "popularity_score": 96,
        "image_url": "https://images.unsplash.com/photo-1589301760014-d929f3979dbc?auto=format&fit=crop&w=800&q=80",
        "description": "Experience the jewelry market turning into a bustling night food street with Gwalior dosa & chocolate sandwiches.",
    },

    # 4. JODHPUR (5 activities)
    {
        "city_name": "Jodhpur",
        "name": "Mehrangarh Fort Exploration",
        "category": "History",
        "duration_hours": 3.0,
        "estimated_cost": 600,
        "rating": 4.9,
        "popularity_score": 98,
        "image_url": "https://images.unsplash.com/photo-1589308078059-be1415eab4c3?auto=format&fit=crop&w=800&q=80",
        "description": "Imposing 15th-century cliff fort with museum artifacts, royal palanquins, and cannon ramparts.",
    },
    {
        "city_name": "Jodhpur",
        "name": "Flying Fox Zipline Over Fort",
        "category": "Adventure",
        "duration_hours": 2.0,
        "estimated_cost": 1800,
        "rating": 4.8,
        "popularity_score": 91,
        "image_url": "https://images.unsplash.com/photo-1507525428034-b723cf961d3e?auto=format&fit=crop&w=800&q=80",
        "description": "Glide across six thrilling ziplines over battlements, desert lakes, and walls of Mehrangarh Fort.",
    },
    {
        "city_name": "Jodhpur",
        "name": "Blue City Photography Walk",
        "category": "Photography",
        "duration_hours": 2.0,
        "estimated_cost": 300,
        "rating": 4.7,
        "popularity_score": 89,
        "image_url": "https://images.unsplash.com/photo-1589308078059-be1415eab4c3?auto=format&fit=crop&w=800&q=80",
        "description": "Navigate labyrinthine indigo-painted alleys around Navchokiya with local photographers.",
    },
    {
        "city_name": "Jodhpur",
        "name": "Jaswant Thada Marble Memorial",
        "category": "Sightseeing",
        "duration_hours": 1.0,
        "estimated_cost": 150,
        "rating": 4.6,
        "popularity_score": 85,
        "image_url": "https://images.unsplash.com/photo-1599661046289-e31897846e41?auto=format&fit=crop&w=800&q=80",
        "description": "Marvel at the intricately carved white marble cenotaph shining in the desert sun with serene gardens.",
    },
    {
        "city_name": "Jodhpur",
        "name": "Umaid Bhawan Palace & Royal Museum",
        "category": "Culture",
        "duration_hours": 2.0,
        "estimated_cost": 400,
        "rating": 4.8,
        "popularity_score": 93,
        "image_url": "https://images.unsplash.com/photo-1615836245337-f5b9b2303f10?auto=format&fit=crop&w=800&q=80",
        "description": "Visit one of the world's largest private residences and view vintage cars, clocks, and royal memorabilia.",
    },

    # 5. JAISALMER (5 activities)
    {
        "city_name": "Jaisalmer",
        "name": "Jaisalmer Living Fort Walk",
        "category": "Culture",
        "duration_hours": 2.5,
        "estimated_cost": 250,
        "rating": 4.8,
        "popularity_score": 95,
        "image_url": "https://images.unsplash.com/photo-1577717903315-1691ae25ab3f?auto=format&fit=crop&w=800&q=80",
        "description": "Explore India's only living fort where thousands reside among carved Jain temples and royal palaces.",
    },
    {
        "city_name": "Jaisalmer",
        "name": "Sam Sand Dunes Desert Safari & Camping",
        "category": "Adventure",
        "duration_hours": 6.0,
        "estimated_cost": 2500,
        "rating": 4.9,
        "popularity_score": 99,
        "image_url": "https://images.unsplash.com/photo-1577717903315-1691ae25ab3f?auto=format&fit=crop&w=800&q=80",
        "description": "Camel trek, 4x4 dune bashing, Rajasthani folk dance by bonfire, and stargazing in desert tents.",
    },
    {
        "city_name": "Jaisalmer",
        "name": "Patwon Ki Haveli Tour",
        "category": "History",
        "duration_hours": 1.5,
        "estimated_cost": 200,
        "rating": 4.7,
        "popularity_score": 88,
        "image_url": "https://images.unsplash.com/photo-1599661046289-e31897846e41?auto=format&fit=crop&w=800&q=80",
        "description": "Witness the finest yellow sandstone filigree work across five opulent merchant mansions.",
    },
    {
        "city_name": "Jaisalmer",
        "name": "Gadisar Lake Boating & Sunrise",
        "category": "Photography",
        "duration_hours": 1.5,
        "estimated_cost": 150,
        "rating": 4.6,
        "popularity_score": 86,
        "image_url": "https://images.unsplash.com/photo-1577717903315-1691ae25ab3f?auto=format&fit=crop&w=800&q=80",
        "description": "Photograph golden shrines and cenotaphs rising from the calm waters of this historic desert reservoir.",
    },
    {
        "city_name": "Jaisalmer",
        "name": "Kuldhara Abandoned Ghost Village",
        "category": "History",
        "duration_hours": 2.0,
        "estimated_cost": 300,
        "rating": 4.5,
        "popularity_score": 84,
        "image_url": "https://images.unsplash.com/photo-1589308078059-be1415eab4c3?auto=format&fit=crop&w=800&q=80",
        "description": "Discover the mysterious abandoned 13th-century desert village cursed and deserted in a single night.",
    },

    # 6. MUMBAI (5 activities)
    {
        "city_name": "Mumbai",
        "name": "Gateway of India & Colaba Causeway",
        "category": "Sightseeing",
        "duration_hours": 2.5,
        "estimated_cost": 300,
        "rating": 4.8,
        "popularity_score": 97,
        "image_url": "https://images.unsplash.com/photo-1570168007204-dfb528c6958f?auto=format&fit=crop&w=800&q=80",
        "description": "Stand before the historic archway, gaze at the Taj Mahal Palace Hotel, and shop vintage trinkets.",
    },
    {
        "city_name": "Mumbai",
        "name": "Marine Drive Sunset Walk",
        "category": "Photography",
        "duration_hours": 1.5,
        "estimated_cost": 0,
        "rating": 4.9,
        "popularity_score": 98,
        "image_url": "https://images.unsplash.com/photo-1570168007204-dfb528c6958f?auto=format&fit=crop&w=800&q=80",
        "description": "Enjoy the sea breeze along the Queen's Necklace promenade as the Mumbai skyline lights up.",
    },
    {
        "city_name": "Mumbai",
        "name": "Elephanta Caves Island Boat Trip",
        "category": "History",
        "duration_hours": 4.0,
        "estimated_cost": 650,
        "rating": 4.7,
        "popularity_score": 91,
        "image_url": "https://images.unsplash.com/photo-1582510003544-4d00b7f74220?auto=format&fit=crop&w=800&q=80",
        "description": "Ferry ride across Mumbai harbor to explore rock-cut UNESCO cave temples dedicated to Lord Shiva.",
    },
    {
        "city_name": "Mumbai",
        "name": "Bandra Street Art & Heritage Cafes",
        "category": "Culture",
        "duration_hours": 2.0,
        "estimated_cost": 450,
        "rating": 4.8,
        "popularity_score": 92,
        "image_url": "https://images.unsplash.com/photo-1514525253161-7a46d19cd819?auto=format&fit=crop&w=800&q=80",
        "description": "Walk past colorful murals on Chapel Road, Portuguese cottages, and celebrity homes.",
    },
    {
        "city_name": "Mumbai",
        "name": "Crawford Market & Street Food Crawl",
        "category": "Food",
        "duration_hours": 2.5,
        "estimated_cost": 500,
        "rating": 4.8,
        "popularity_score": 95,
        "image_url": "https://images.unsplash.com/photo-1601050690597-df0568f70950?auto=format&fit=crop&w=800&q=80",
        "description": "Sample Mumbai's iconic Vada Pav, Pav Bhaji, Bun Maska, and fresh seasonal Alphonso mangoes.",
    },

    # 7. DELHI (5 activities)
    {
        "city_name": "Delhi",
        "name": "India Gate & Kartavya Path Walk",
        "category": "Sightseeing",
        "duration_hours": 1.5,
        "estimated_cost": 0,
        "rating": 4.7,
        "popularity_score": 96,
        "image_url": "https://images.unsplash.com/photo-1587474260584-136574528ed5?auto=format&fit=crop&w=800&q=80",
        "description": "Honor India's soldiers at the Amar Jawan Jyoti arch and stroll the grand illuminated boulevard.",
    },
    {
        "city_name": "Delhi",
        "name": "Qutub Minar & Mehrauli Heritage",
        "category": "History",
        "duration_hours": 2.0,
        "estimated_cost": 300,
        "rating": 4.8,
        "popularity_score": 95,
        "image_url": "https://images.unsplash.com/photo-1587474260584-136574528ed5?auto=format&fit=crop&w=800&q=80",
        "description": "Examine the world's tallest brick minaret and ancient rust-free iron pillar standing since the 4th century.",
    },
    {
        "city_name": "Delhi",
        "name": "Old Delhi Chandni Chowk Food Walk",
        "category": "Food",
        "duration_hours": 2.5,
        "estimated_cost": 600,
        "rating": 4.9,
        "popularity_score": 98,
        "image_url": "https://images.unsplash.com/photo-1589301760014-d929f3979dbc?auto=format&fit=crop&w=800&q=80",
        "description": "Feast on Paranthe Wali Gali delicacies, Karim's kebabs, Natraj dahi bhalla, and jalebis.",
    },
    {
        "city_name": "Delhi",
        "name": "Red Fort Mughal Citadel",
        "category": "History",
        "duration_hours": 2.5,
        "estimated_cost": 350,
        "rating": 4.8,
        "popularity_score": 96,
        "image_url": "https://images.unsplash.com/photo-1587474260584-136574528ed5?auto=format&fit=crop&w=800&q=80",
        "description": "Tour the massive red sandstone fortress, Diwan-i-Aam, and historic sound and light show.",
    },
    {
        "city_name": "Delhi",
        "name": "Humayun's Tomb Garden Complex",
        "category": "Photography",
        "duration_hours": 2.0,
        "estimated_cost": 300,
        "rating": 4.9,
        "popularity_score": 94,
        "image_url": "https://images.unsplash.com/photo-1564507592333-c60657eea523?auto=format&fit=crop&w=800&q=80",
        "description": "Marvel at the precursor to the Taj Mahal set within symmetrical Charbagh Persian gardens.",
    },

    # 8. GOA (5 activities)
    {
        "city_name": "Goa",
        "name": "North Goa Beach Water Sports (Baga & Calangute)",
        "category": "Adventure",
        "duration_hours": 3.5,
        "estimated_cost": 2200,
        "rating": 4.8,
        "popularity_score": 98,
        "image_url": "https://images.unsplash.com/photo-1512343879784-a960bf40e7f2?auto=format&fit=crop&w=800&q=80",
        "description": "Parasailing, jet skiing, bumper boat rides, and banana tube rides over turquoise Arabian waters.",
    },
    {
        "city_name": "Goa",
        "name": "Fontainhas Latin Quarter Walking Tour",
        "category": "Photography",
        "duration_hours": 2.0,
        "estimated_cost": 400,
        "rating": 4.7,
        "popularity_score": 92,
        "image_url": "https://images.unsplash.com/photo-1587974928442-77dc3e0dba72?auto=format&fit=crop&w=800&q=80",
        "description": "Walk among colorful Portuguese villas with tiled roofs, hanging wooden balconies, and cafes.",
    },
    {
        "city_name": "Goa",
        "name": "Dudhsagar Waterfalls Jungle Safari",
        "category": "Nature",
        "duration_hours": 6.0,
        "estimated_cost": 1800,
        "rating": 4.9,
        "popularity_score": 97,
        "image_url": "https://images.unsplash.com/photo-1546853020-ca4909aef454?auto=format&fit=crop&w=800&q=80",
        "description": "Off-road drive through Mollem National Park to swim in natural pools beneath the 4-tiered waterfalls.",
    },
    {
        "city_name": "Goa",
        "name": "Fort Aguada & Lighthouse Sunset",
        "category": "Sightseeing",
        "duration_hours": 2.0,
        "estimated_cost": 150,
        "rating": 4.7,
        "popularity_score": 93,
        "image_url": "https://images.unsplash.com/photo-1512343879784-a960bf40e7f2?auto=format&fit=crop&w=800&q=80",
        "description": "17th-century Portuguese fortress overlooking Sinquerim Beach with panoramic coastal ocean views.",
    },
    {
        "city_name": "Goa",
        "name": "Goan Fish Curry & Beach Shack Dining",
        "category": "Food",
        "duration_hours": 2.0,
        "estimated_cost": 800,
        "rating": 4.8,
        "popularity_score": 95,
        "image_url": "https://images.unsplash.com/photo-1589301760014-d929f3979dbc?auto=format&fit=crop&w=800&q=80",
        "description": "Savor authentic Kingfish recheado, prawn balchao, pork vindaloo, and bebinca at sunset.",
    },

    # 9. AGRA (5 activities)
    {
        "city_name": "Agra",
        "name": "Taj Mahal Sunrise Experience",
        "category": "Sightseeing",
        "duration_hours": 3.0,
        "estimated_cost": 1100,
        "rating": 5.0,
        "popularity_score": 100,
        "image_url": "https://images.unsplash.com/photo-1564507592333-c60657eea523?auto=format&fit=crop&w=800&q=80",
        "description": "Experience the ivory-white marble monument to eternal love bathed in the golden morning light.",
    },
    {
        "city_name": "Agra",
        "name": "Agra Fort Mughal Dynasty Tour",
        "category": "History",
        "duration_hours": 2.0,
        "estimated_cost": 450,
        "rating": 4.7,
        "popularity_score": 93,
        "image_url": "https://images.unsplash.com/photo-1564507592333-c60657eea523?auto=format&fit=crop&w=800&q=80",
        "description": "Tour the formidable red sandstone citadel that served as the principal residence of Mughal Emperors.",
    },
    {
        "city_name": "Agra",
        "name": "Mehtab Bagh Moonlight River View",
        "category": "Photography",
        "duration_hours": 1.5,
        "estimated_cost": 200,
        "rating": 4.8,
        "popularity_score": 91,
        "image_url": "https://images.unsplash.com/photo-1564507592333-c60657eea523?auto=format&fit=crop&w=800&q=80",
        "description": "Capture mirror reflections of the Taj Mahal across the Yamuna River from the botanical gardens.",
    },
    {
        "city_name": "Agra",
        "name": "Fatehpur Sikri Royal City Tour",
        "category": "History",
        "duration_hours": 3.0,
        "estimated_cost": 500,
        "rating": 4.7,
        "popularity_score": 90,
        "image_url": "https://images.unsplash.com/photo-1599661046289-e31897846e41?auto=format&fit=crop&w=800&q=80",
        "description": "Explore Emperor Akbar's abandoned sandstone capital, Buland Darwaza, and Salim Chishti Dargah.",
    },
    {
        "city_name": "Agra",
        "name": "Agra Petha & Mughlai Food Trail",
        "category": "Food",
        "duration_hours": 2.0,
        "estimated_cost": 400,
        "rating": 4.6,
        "popularity_score": 86,
        "image_url": "https://images.unsplash.com/photo-1589301760014-d929f3979dbc?auto=format&fit=crop&w=800&q=80",
        "description": "Sample legendary Agra Petha sweets in Kesar and Angoori flavors and rich Mughlai parathas.",
    },

    # 10. VARANASI (5 activities)
    {
        "city_name": "Varanasi",
        "name": "Dashashwamedh Ghat Evening Ganga Aarti",
        "category": "Culture",
        "duration_hours": 2.0,
        "estimated_cost": 200,
        "rating": 4.9,
        "popularity_score": 99,
        "image_url": "https://images.unsplash.com/photo-1561359313-0639aad49ca6?auto=format&fit=crop&w=800&q=80",
        "description": "Witness the spellbinding choreographed fire ritual performed by priests with brass lamps on the river.",
    },
    {
        "city_name": "Varanasi",
        "name": "Dawn Boat Ride on the Holy Ganges",
        "category": "Photography",
        "duration_hours": 2.0,
        "estimated_cost": 500,
        "rating": 4.9,
        "popularity_score": 97,
        "image_url": "https://images.unsplash.com/photo-1561359313-0639aad49ca6?auto=format&fit=crop&w=800&q=80",
        "description": "Glide along ancient ghats at sunrise as morning bathers, chants, and mist create timeless magic.",
    },
    {
        "city_name": "Varanasi",
        "name": "Kashi Vishwanath Corridor & Temple",
        "category": "Culture",
        "duration_hours": 2.0,
        "estimated_cost": 300,
        "rating": 4.8,
        "popularity_score": 96,
        "image_url": "https://images.unsplash.com/photo-1561359313-0639aad49ca6?auto=format&fit=crop&w=800&q=80",
        "description": "Visit one of the 12 sacred Jyotirlingas with gold-plated spires and modern grand pilgrim plaza.",
    },
    {
        "city_name": "Varanasi",
        "name": "Sarnath Buddhist Stupa & Museum Tour",
        "category": "History",
        "duration_hours": 3.0,
        "estimated_cost": 250,
        "rating": 4.7,
        "popularity_score": 92,
        "image_url": "https://images.unsplash.com/photo-1587474260584-136574528ed5?auto=format&fit=crop&w=800&q=80",
        "description": "Stand where Lord Buddha gave his first sermon; see the Dhamek Stupa and Ashoka Lion Capital.",
    },
    {
        "city_name": "Varanasi",
        "name": "Banarasi Silk Weaving & Street Food Trail",
        "category": "Food",
        "duration_hours": 2.5,
        "estimated_cost": 450,
        "rating": 4.8,
        "popularity_score": 94,
        "image_url": "https://images.unsplash.com/photo-1589301760014-d929f3979dbc?auto=format&fit=crop&w=800&q=80",
        "description": "Watch master handloom weavers craft pure Zari sarees, followed by Malaiyo and Tamatar Chaat.",
    },

    # 11. SRINAGAR (5 activities)
    {
        "city_name": "Srinagar",
        "name": "Dal Lake Shikara Ride at Dawn",
        "category": "Nature",
        "duration_hours": 2.0,
        "estimated_cost": 700,
        "rating": 4.9,
        "popularity_score": 98,
        "image_url": "https://images.unsplash.com/photo-1595815771614-ade9d652a65d?auto=format&fit=crop&w=800&q=80",
        "description": "Glide through floating vegetable markets and lotus gardens on a traditional wooden boat.",
    },
    {
        "city_name": "Srinagar",
        "name": "Mughal Gardens Nishat & Shalimar Tour",
        "category": "Sightseeing",
        "duration_hours": 2.5,
        "estimated_cost": 200,
        "rating": 4.8,
        "popularity_score": 94,
        "image_url": "https://images.unsplash.com/photo-1595815771614-ade9d652a65d?auto=format&fit=crop&w=800&q=80",
        "description": "Terraced lawns, cascading fountains, and centuries-old Chinar trees overlooking Dal Lake.",
    },
    {
        "city_name": "Srinagar",
        "name": "Shankaracharya Hilltop Temple Trek",
        "category": "Culture",
        "duration_hours": 2.0,
        "estimated_cost": 150,
        "rating": 4.7,
        "popularity_score": 90,
        "image_url": "https://images.unsplash.com/photo-1595815771614-ade9d652a65d?auto=format&fit=crop&w=800&q=80",
        "description": "Ancient Shiva shrine on Gopadari Hill offering panoramic views of Srinagar and Pir Panjal.",
    },
    {
        "city_name": "Srinagar",
        "name": "Traditional Kashmiri Wazwan Feast",
        "category": "Food",
        "duration_hours": 2.0,
        "estimated_cost": 1200,
        "rating": 4.9,
        "popularity_score": 95,
        "image_url": "https://images.unsplash.com/photo-1589301760014-d929f3979dbc?auto=format&fit=crop&w=800&q=80",
        "description": "Indulge in a 36-course royal Kashmiri banquet featuring Rogan Josh, Gushtaba, and saffron Kahwa.",
    },
    {
        "city_name": "Srinagar",
        "name": "Old Srinagar Wooden Bridges & Pashmina Walk",
        "category": "Photography",
        "duration_hours": 2.0,
        "estimated_cost": 300,
        "rating": 4.6,
        "popularity_score": 88,
        "image_url": "https://images.unsplash.com/photo-1595815771614-ade9d652a65d?auto=format&fit=crop&w=800&q=80",
        "description": "Photograph historic wooden architecture along Jhelum River and shop genuine Cashmere shawls.",
    },

    # 12. AMRITSAR (5 activities)
    {
        "city_name": "Amritsar",
        "name": "Golden Temple (Harmandir Sahib) & Langar",
        "category": "Culture",
        "duration_hours": 3.0,
        "estimated_cost": 0,
        "rating": 5.0,
        "popularity_score": 100,
        "image_url": "https://images.unsplash.com/photo-1584551246679-0daf3d275d0f?auto=format&fit=crop&w=800&q=80",
        "description": "Experience divine serenity at the gilded sanctum surrounded by Amrit Sarovar lake and community kitchen.",
    },
    {
        "city_name": "Amritsar",
        "name": "Wagah Border Beating Retreat Ceremony",
        "category": "Sightseeing",
        "duration_hours": 3.5,
        "estimated_cost": 400,
        "rating": 4.9,
        "popularity_score": 98,
        "image_url": "https://images.unsplash.com/photo-1584551246679-0daf3d275d0f?auto=format&fit=crop&w=800&q=80",
        "description": "Electrifying patriotic flag-lowering military drill ceremony between Indian BSF and Pakistan Rangers.",
    },
    {
        "city_name": "Amritsar",
        "name": "Jallianwala Bagh Historic Memorial",
        "category": "History",
        "duration_hours": 1.5,
        "estimated_cost": 50,
        "rating": 4.8,
        "popularity_score": 93,
        "image_url": "https://images.unsplash.com/photo-1584551246679-0daf3d275d0f?auto=format&fit=crop&w=800&q=80",
        "description": "Pay homage at the national memorial preserving bullet marks and the Martyrs' Well from 1919.",
    },
    {
        "city_name": "Amritsar",
        "name": "Authentic Amritsari Kulcha & Lassi Trail",
        "category": "Food",
        "duration_hours": 2.0,
        "estimated_cost": 300,
        "rating": 4.9,
        "popularity_score": 97,
        "image_url": "https://images.unsplash.com/photo-1601050690597-df0568f70950?auto=format&fit=crop&w=800&q=80",
        "description": "Crisp tandoori butter-loaded kulchas stuffed with spiced potatoes and a giant glass of sweet lassi.",
    },
    {
        "city_name": "Amritsar",
        "name": "Partition Museum Tour in Town Hall",
        "category": "History",
        "duration_hours": 2.0,
        "estimated_cost": 150,
        "rating": 4.7,
        "popularity_score": 89,
        "image_url": "https://images.unsplash.com/photo-1584551246679-0daf3d275d0f?auto=format&fit=crop&w=800&q=80",
        "description": "World's first museum dedicated to the 1947 Partition with oral histories, letters, and artifacts.",
    },

    # 13. KOCHI (5 activities)
    {
        "city_name": "Kochi",
        "name": "Fort Kochi Chinese Fishing Nets & Sunset",
        "category": "Photography",
        "duration_hours": 1.5,
        "estimated_cost": 100,
        "rating": 4.8,
        "popularity_score": 95,
        "image_url": "https://images.unsplash.com/photo-1602216056096-3b40cc0c9944?auto=format&fit=crop&w=800&q=80",
        "description": "Iconic teak and bamboo cantilevered fishing nets operating along the Vasco da Gama Square coast.",
    },
    {
        "city_name": "Kochi",
        "name": "Mattancherry Dutch Palace & Jew Town",
        "category": "History",
        "duration_hours": 2.5,
        "estimated_cost": 200,
        "rating": 4.7,
        "popularity_score": 91,
        "image_url": "https://images.unsplash.com/photo-1602216056096-3b40cc0c9944?auto=format&fit=crop&w=800&q=80",
        "description": "Marvel at 16th-century Ramayana murals, ancient Paradesi Synagogue, and antique spice warehouses.",
    },
    {
        "city_name": "Kochi",
        "name": "Kerala Kathakali Live Dance & Makeup",
        "category": "Culture",
        "duration_hours": 2.0,
        "estimated_cost": 450,
        "rating": 4.9,
        "popularity_score": 96,
        "image_url": "https://images.unsplash.com/photo-1582510003544-4d00b7f74220?auto=format&fit=crop&w=800&q=80",
        "description": "Watch master performers apply intricate facial makeup followed by dramatic story-play and mudras.",
    },
    {
        "city_name": "Kochi",
        "name": "Kerala Backwater Kayaking Tour",
        "category": "Adventure",
        "duration_hours": 3.0,
        "estimated_cost": 1500,
        "rating": 4.8,
        "popularity_score": 94,
        "image_url": "https://images.unsplash.com/photo-1507525428034-b723cf961d3e?auto=format&fit=crop&w=800&q=80",
        "description": "Paddle through serene village canals shaded by coconut palms and water lilies.",
    },
    {
        "city_name": "Kochi",
        "name": "Kerala Sadhya & Seafood Coastal Trail",
        "category": "Food",
        "duration_hours": 2.0,
        "estimated_cost": 650,
        "rating": 4.8,
        "popularity_score": 93,
        "image_url": "https://images.unsplash.com/photo-1589301760014-d929f3979dbc?auto=format&fit=crop&w=800&q=80",
        "description": "Traditional 24-dish vegetarian Sadhya feast on a banana leaf followed by Karimeen Pollichathu.",
    },

    # 14. OOTY (5 activities)
    {
        "city_name": "Ooty",
        "name": "Nilgiri Mountain Toy Train Ride",
        "category": "Sightseeing",
        "duration_hours": 2.5,
        "estimated_cost": 350,
        "rating": 4.9,
        "popularity_score": 98,
        "image_url": "https://images.unsplash.com/photo-1589182373726-e4f658ab50f0?auto=format&fit=crop&w=800&q=80",
        "description": "UNESCO World Heritage steam train journey climbing mist-covered valleys and eucalyptus forests.",
    },
    {
        "city_name": "Ooty",
        "name": "Doddabetta Peak & Telescope House",
        "category": "Nature",
        "duration_hours": 2.0,
        "estimated_cost": 150,
        "rating": 4.7,
        "popularity_score": 92,
        "image_url": "https://images.unsplash.com/photo-1589182373726-e4f658ab50f0?auto=format&fit=crop&w=800&q=80",
        "description": "Stand at the highest summit in the Nilgiris (2,637 m) overlooking the rolling tea estates of Tamil Nadu.",
    },
    {
        "city_name": "Ooty",
        "name": "Ooty Botanical & Rose Gardens",
        "category": "Photography",
        "duration_hours": 2.0,
        "estimated_cost": 100,
        "rating": 4.6,
        "popularity_score": 89,
        "image_url": "https://images.unsplash.com/photo-1589182373726-e4f658ab50f0?auto=format&fit=crop&w=800&q=80",
        "description": "Explore 55 acres of terraced gardens featuring exotic flora, fossil trees, and over 20,000 rose varieties.",
    },
    {
        "city_name": "Ooty",
        "name": "Pykara Lake Boating & Waterfalls",
        "category": "Adventure",
        "duration_hours": 3.0,
        "estimated_cost": 500,
        "rating": 4.8,
        "popularity_score": 94,
        "image_url": "https://images.unsplash.com/photo-1506744038136-46273834b3fb?auto=format&fit=crop&w=800&q=80",
        "description": "Speed boating across pristine lake waters and hiking down to the multi-tiered Pykara falls.",
    },
    {
        "city_name": "Ooty",
        "name": "Nilgiri Tea Factory & Chocolate Tasting",
        "category": "Food",
        "duration_hours": 1.5,
        "estimated_cost": 250,
        "rating": 4.7,
        "popularity_score": 91,
        "image_url": "https://images.unsplash.com/photo-1589301760014-d929f3979dbc?auto=format&fit=crop&w=800&q=80",
        "description": "Watch tea leaf processing from harvest to brew and sample handmade artisan Ooty chocolates.",
    },

    # 15. DARJEELING (5 activities)
    {
        "city_name": "Darjeeling",
        "name": "Tiger Hill Kanchenjunga Sunrise",
        "category": "Photography",
        "duration_hours": 2.5,
        "estimated_cost": 400,
        "rating": 4.9,
        "popularity_score": 99,
        "image_url": "https://images.unsplash.com/photo-1544735716-392fe2489ffa?auto=format&fit=crop&w=800&q=80",
        "description": "Witness the first golden rays of sunlight illuminating the world's 3rd highest peak, Mt. Kanchenjunga.",
    },
    {
        "city_name": "Darjeeling",
        "name": "Batasia Loop & War Memorial Toy Train",
        "category": "Sightseeing",
        "duration_hours": 1.5,
        "estimated_cost": 250,
        "rating": 4.8,
        "popularity_score": 95,
        "image_url": "https://images.unsplash.com/photo-1544735716-392fe2489ffa?auto=format&fit=crop&w=800&q=80",
        "description": "Famous 360-degree railway loop wrapped in manicured flower beds with views of the Himalayan ranges.",
    },
    {
        "city_name": "Darjeeling",
        "name": "Happy Valley Tea Estate Plucking & Tour",
        "category": "Nature",
        "duration_hours": 2.0,
        "estimated_cost": 300,
        "rating": 4.7,
        "popularity_score": 92,
        "image_url": "https://images.unsplash.com/photo-1544735716-392fe2489ffa?auto=format&fit=crop&w=800&q=80",
        "description": "Walk among organic tea bushes established in 1854 and taste exquisite Muscatel first-flush teas.",
    },
    {
        "city_name": "Darjeeling",
        "name": "Himalayan Mountaineering Institute & Zoo",
        "category": "Adventure",
        "duration_hours": 2.5,
        "estimated_cost": 200,
        "rating": 4.8,
        "popularity_score": 94,
        "image_url": "https://images.unsplash.com/photo-1544735716-392fe2489ffa?auto=format&fit=crop&w=800&q=80",
        "description": "Tenzing Norgay memorial museum and high-altitude wildlife conservation center for Red Pandas & Snow Leopards.",
    },
    {
        "city_name": "Darjeeling",
        "name": "Darjeeling Ropeway Cable Car Ride",
        "category": "Sightseeing",
        "duration_hours": 1.5,
        "estimated_cost": 350,
        "rating": 4.8,
        "popularity_score": 96,
        "image_url": "https://images.unsplash.com/photo-1544735716-392fe2489ffa?auto=format&fit=crop&w=800&q=80",
        "description": "Soar high over cascading river valleys, dense forests, and tea gardens aboard India's oldest ropeway.",
    },
]


def seed_database():
    Base.metadata.create_all(bind=engine)
    db = SessionLocal()

    try:
        # 1. Seed & Update Cities
        for city_data in CITIES_DATA:
            existing = db.query(City).filter(City.name == city_data["name"]).first()
            img_url = get_city_image(city_data["name"])
            if not existing:
                city = City(
                    name=city_data["name"],
                    state=city_data["state"],
                    country="India",
                    region=city_data["region"],
                    description=city_data["description"],
                    image_url=img_url,
                    cost_index=city_data["cost_index"],
                    popularity=city_data["popularity"],
                    latitude=city_data["latitude"],
                    longitude=city_data["longitude"],
                    best_suited_interests=city_data["best_suited_interests"],
                )
                db.add(city)
            else:
                existing.image_url = img_url
                existing.region = city_data["region"]
                existing.description = city_data["description"]
                existing.state = city_data["state"]
                existing.cost_index = city_data["cost_index"]
                existing.popularity = city_data["popularity"]
        db.commit()

        # 2. Seed & Update Activities with exact photos
        for act_data in ACTIVITIES_DATA:
            city = db.query(City).filter(City.name == act_data["city_name"]).first()
            if city:
                existing_act = db.query(Activity).filter(Activity.city_id == city.id, Activity.name == act_data["name"]).first()
                act_img = act_data.get("image_url") or get_category_image(act_data["category"])
                if not existing_act:
                    act = Activity(
                        city_id=city.id,
                        name=act_data["name"],
                        category=act_data["category"],
                        duration_hours=act_data["duration_hours"],
                        estimated_cost=act_data["estimated_cost"],
                        rating=act_data["rating"],
                        popularity_score=act_data["popularity_score"],
                        description=act_data["description"],
                        image_url=act_img,
                    )
                    db.add(act)
                else:
                    existing_act.image_url = act_img
                    existing_act.description = act_data["description"]
                    existing_act.estimated_cost = act_data["estimated_cost"]
                    existing_act.duration_hours = act_data["duration_hours"]
                    existing_act.rating = act_data["rating"]
                    existing_act.category = act_data["category"]
        db.commit()

        # 3. Seed Demo Users
        admin_user = db.query(User).filter(User.email == "admin@globetrotter.com").first()
        if not admin_user:
            admin_user = User(
                email="admin@globetrotter.com",
                hashed_password=get_password_hash("Admin@12345"),
                first_name="Admin",
                last_name="Superuser",
                role="admin",
                language="English",
                travel_style="Luxury",
                budget_preference="Luxury",
                interests="History,Culture,Photography,Nature",
            )
            db.add(admin_user)

        demo_user = db.query(User).filter(User.email == "user@globetrotter.com").first()
        if not demo_user:
            demo_user = User(
                email="user@globetrotter.com",
                hashed_password=get_password_hash("User@12345"),
                first_name="Aarav",
                last_name="Sharma",
                role="user",
                city="Mumbai",
                country="India",
                language="English",
                travel_style="Standard",
                budget_preference="Moderate",
                interests="History,Culture,Food,Nature,Adventure",
            )
            db.add(demo_user)
        db.commit()

        # 4. Seed Rajasthan Explorer Trip for demo user
        if demo_user:
            existing_trip = db.query(Trip).filter(Trip.user_id == demo_user.id, Trip.title == "Rajasthan Explorer (My Plan)").first()
            if not existing_trip:
                today = datetime.date.today()
                start_d = today + datetime.timedelta(days=14)
                end_d = start_d + datetime.timedelta(days=6)

                jaipur = db.query(City).filter(City.name == "Jaipur").first()
                jodhpur = db.query(City).filter(City.name == "Jodhpur").first()
                udaipur = db.query(City).filter(City.name == "Udaipur").first()

                trip = Trip(
                    user_id=demo_user.id,
                    title="Rajasthan Explorer (My Plan)",
                    start_date=start_d,
                    end_date=end_d,
                    overall_budget=45000,
                    travel_style="Standard",
                    description="Classic Golden Triangle and royal heritage tour across Jaipur, Jodhpur, and Udaipur.",
                    cover_image="https://images.unsplash.com/photo-1599661046289-e31897846e41?auto=format&fit=crop&w=1200&q=80",
                    status="upcoming",
                    is_public=False,
                )
                db.add(trip)
                db.commit()
                db.refresh(trip)

                if jaipur:
                    s1 = TripStop(
                        trip_id=trip.id,
                        city_id=jaipur.id,
                        arrival_date=start_d,
                        departure_date=start_d + datetime.timedelta(days=2),
                        travel_mode="Flight",
                        travel_cost=4500,
                        order_index=0,
                        notes="Arrival in Pink City. Visit Amber Fort and Hawa Mahal.",
                    )
                    db.add(s1)

                if jodhpur:
                    s2 = TripStop(
                        trip_id=trip.id,
                        city_id=jodhpur.id,
                        arrival_date=start_d + datetime.timedelta(days=2),
                        departure_date=start_d + datetime.timedelta(days=4),
                        travel_mode="Train",
                        travel_cost=800,
                        order_index=1,
                        notes="Vande Bharat express train from Jaipur to Blue City Jodhpur.",
                    )
                    db.add(s2)

                if udaipur:
                    s3 = TripStop(
                        trip_id=trip.id,
                        city_id=udaipur.id,
                        arrival_date=start_d + datetime.timedelta(days=4),
                        departure_date=end_d,
                        travel_mode="Car",
                        travel_cost=2500,
                        order_index=2,
                        notes="Private cab via Ranakpur Jain Temples to Udaipur City of Lakes.",
                    )
                    db.add(s3)

                db.commit()

                # Seed sample Itinerary Activities
                amber_act = db.query(Activity).filter(Activity.name == "Amber Fort Guided Tour").first()
                if amber_act:
                    ia1 = ItineraryActivity(
                        trip_id=trip.id,
                        activity_id=amber_act.id,
                        date=start_d,
                        start_time="09:30",
                        end_time="12:30",
                        estimated_cost=500,
                        notes="Guided walk with local audio headset.",
                        order_index=0,
                    )
                    db.add(ia1)

                hawa_act = db.query(Activity).filter(Activity.name == "Hawa Mahal & Old City Walk").first()
                if hawa_act:
                    ia2 = ItineraryActivity(
                        trip_id=trip.id,
                        activity_id=hawa_act.id,
                        date=start_d,
                        start_time="15:00",
                        end_time="17:00",
                        estimated_cost=200,
                        notes="Photograph pink sandstone facade from Wind View Cafe.",
                        order_index=1,
                    )
                    db.add(ia2)

                # Seed sample expenses
                db.add(Expense(trip_id=trip.id, category="Transport", description="IndiGo Flight to Jaipur", amount=4500, date=start_d))
                db.add(Expense(trip_id=trip.id, category="Accommodation", description="Heritage Haveli Stay (Jaipur)", amount=6000, date=start_d))
                db.add(Expense(trip_id=trip.id, category="Activities", description="Amber Fort Entry & Guide", amount=500, date=start_d))
                db.add(Expense(trip_id=trip.id, category="Food", description="Dinner at Chokhi Dhani", amount=1200, date=start_d))

                db.commit()

        print("[GlobeTrotter] Database seeded successfully with verified Indian destinations, activities & photography!")
    except Exception as e:
        print(f"[GlobeTrotter Seed Warning]: {e}")
        db.rollback()
    finally:
        db.close()
